name: Generate and Deploy Website

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Clone and build rl-lang
        run: |
          git clone --branch dev https://github.com/rl-lang/rl-lang.git
          cd rl-lang
          cargo build --release
          sudo cp target/release/rl /usr/local/bin/rl

      - name: Generate index.html
        run: rl dev > index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          include_files: index.html
